language: java

services:
  - docker

script:
  - docker build -t msadel/ecar --build-arg APP=eCar .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push msadel/ecar

after_success:
  - bash <(curl -s https://codecov.io/bash)

